[build]
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "https://mass-effect-api.fly.dev/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


